### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by zaoqi** [lonnng/lua-rs#7]

**Comment by lonng** [comment]
It just compiles the *.lua to `instructions`, and runtime does not implement yet.

**Comment by zaoqi** [comment]
What `IL`?

**Comment by lonng** [comment]
@zaoqi Sorry for misleading you in the above comment, I have corrected it.

**Comment by zaoqi** [comment]
like `luac`?

**Comment by lonng** [comment]
@zaoqi Yes
